name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build gateway-service
        run: mvn -f gateway-service/gateway-service/pom.xml clean package -DskipTests

      - name: Build orders-service
        run: mvn -f orders/orders/pom.xml clean package -DskipTests

      - name: Build usage-service
        run: mvn -f user-service/user-service/pom.xml clean package -DskipTests

      - name: Build billing-service
        run: mvn -f billing-service/billing-service/pom.xml clean package -DskipTests

      - name: Build Docker images
        run: |
          docker build -t gateway-service ./gateway-service/gateway-service
          docker build -t orders-service ./orders/orders-service
          docker build -t usage-service ./user-service/user-service
          docker build -t billing-service ./billing-service/billing-service